pref("extensions.paymott.apikey", "");
pref("extensions.paymott.username", "");
pref("extensions.paymott.autoLogin", true);
pref("extensions.paymott.panelShow", true);
pref("extensions.paymott.panelFormat", "%p - %t");
pref("extensions.paymott.iconAnimate", true);
pref("extensions.paymott.rememberTask", true);
pref("extensions.paymott.fastStart", false);
pref("extensions.paymott.timeDescription", "by Paymo Time Tracker FF addon");
pref("extensions.paymott.lastTask", 0);
pref("extensions.paymott.debug", false);
